#!/bin/bash
/show/description "Configure dhcp for wlan0"

/do/dhcpd/install

/show/listecho "Modify /etc/dhcp/dhcpd.conf" $OK
/system/autoBackup "/etc/dhcp/dhcpd.conf"
cat <<\EOF > /etc/dhcp/dhcpd.conf &&
# SERVE IP ADDRESS TO WLAN0 (For HOTSPOT see github.com/pigetnet/dhcpd)
# Source : https://learn.adafruit.com/setting-up-a-raspberry-pi-as-a-wifi-access-point/install-software

ddns-update-style none;
default-lease-time 600;
max-lease-time 7200;
authoritative;
log-facility local7;

subnet 192.168.42.0 netmask 255.255.255.0 {
        range 192.168.42.10 192.168.42.50;
        option broadcast-address 192.168.42.255;
        option routers 192.168.42.1;
        default-lease-time 600;
        max-lease-time 7200;
        option domain-name "local";
        option domain-name-servers 8.8.8.8, 8.8.4.4;
}

EOF

/show/listecho "Modify /etc/default/isc-dhcp-server" $OK
/system/autoBackup "/etc/default/isc-dhcp-server"
cat <<\EOF > /etc/default/isc-dhcp-server &&
# SERVE IP ADDRESS TO WLAN0 (For HOTSPOT see github.com/pigetnet/dhcpd)
# Source : https://learn.adafruit.com/setting-up-a-raspberry-pi-as-a-wifi-access-point/install-software
INTERFACES="wlan0"

EOF

/show/nlbecho ""